/**************************************************
 * FileName - AcqPartnerIntPortType.java
 *
 * (c) Disney. All rights reserved.
 *
 * $Author: ppaparin $
 * $Revision: #1 $
 * $Change: 1580469 $
 * $Date: 2015/06/12 $
 **************************************************/
package ar.project.webServ.area.disney;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.0.
 * 2015-06-10T18:34:08.778-03:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://cig.jpmchase.net/20110218/card/acq/", name = "AcqPartnerIntPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AcqPartnerIntPortType {

    /**
     * @param postAppStatusRequest object
     * @return appStatusResponse object
     */
    @WebResult(name = "postAppStatusResponse", targetNamespace = "http://cig.jpmchase.net/20110218/card/acq/", partName = "postAppStatusResponse")
    @WebMethod(action = "http://cig.jpmchase.net/20110218/card/acq/postAppStatus")
    public AppStatusResponse postAppStatus(
        @WebParam(partName = "postAppStatusRequest", name = "postAppStatusRequest")
        AppStatusRequest postAppStatusRequest
    );
}
