/**************************************************
 * FileName - AcqPartnerIntPortImpl.java
 *
 * (c) Disney. All rights reserved.
 *
 * $Author: ppaparin $
 * $Revision: #1 $
 * $Change: 1580469 $
 * $Date: 2015/06/12 $
 **************************************************/
package ar.project.webServ.area.disney;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.0 2015-06-10T18:34:08.715-03:00.
 * Generated source version: 3.1.0
 * 
 */
@javax.jws.WebService(targetNamespace = "http://cig.jpmchase.net/20110218/card/acq/", endpointInterface = "ar.project.webServ.area.disney.AcqPartnerIntPortType")
public class AcqPartnerIntPortImpl implements AcqPartnerIntPortType {

	private static final Logger LOG = Logger
			.getLogger(AcqPartnerIntPortImpl.class.getName());

	/**
	 * This method was generated by Apache CXF 3.1.0
	 * 2015-06-10T18:34:08.715-03:00. Generated source version: 3.1.0
	 * 
	 * @param postAppStatusRequest
	 *            object
	 * @return AppStatusResponse object
	 */
	public AppStatusResponse postAppStatus(
			AppStatusRequest postAppStatusRequest) {
		LOG.info("Executing operation postAppStatus");

		AppStatusResponse asr = new AppStatusResponse();
		WebServiceResponse wsr = new WebServiceResponse();
		wsr.setResponseMessage("OK");
		wsr.setTraceIdentifier("DONEJOB1");
		asr.setResponse(wsr);
		return asr;

	}

}
