package ar.project.wclie.area;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-12-02T19:51:52.397-03:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "MathModuleImplService", 
                  wsdlLocation = "file:/tmp/tempdir1732865431285469021.tmp/MathModule_1.wsdl",
                  targetNamespace = "http://area.webServ.project.ar/") 
public class MathModuleImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://area.webServ.project.ar/", "MathModuleImplService");
    public final static QName MathModuleImplPort = new QName("http://area.webServ.project.ar/", "MathModuleImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/tmp/tempdir1732865431285469021.tmp/MathModule_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MathModuleImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/tmp/tempdir1732865431285469021.tmp/MathModule_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MathModuleImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MathModuleImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathModuleImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MathModuleImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MathModuleImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MathModuleImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MathModule
     */
    @WebEndpoint(name = "MathModuleImplPort")
    public MathModule getMathModuleImplPort() {
        return super.getPort(MathModuleImplPort, MathModule.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathModule
     */
    @WebEndpoint(name = "MathModuleImplPort")
    public MathModule getMathModuleImplPort(WebServiceFeature... features) {
        return super.getPort(MathModuleImplPort, MathModule.class, features);
    }

}
