package ar.project.wclie.area;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-12-02T19:51:52.373-03:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://area.webServ.project.ar/", name = "MathModule")
@XmlSeeAlso({ObjectFactory.class})
public interface MathModule {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "isOdd", targetNamespace = "http://area.webServ.project.ar/", className = "ar.project.wclie.area.IsOdd")
    @WebMethod
    @ResponseWrapper(localName = "isOddResponse", targetNamespace = "http://area.webServ.project.ar/", className = "ar.project.wclie.area.IsOddResponse")
    public boolean isOdd(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPersonas", targetNamespace = "http://area.webServ.project.ar/", className = "ar.project.wclie.area.GetPersonas")
    @WebMethod
    @ResponseWrapper(localName = "getPersonasResponse", targetNamespace = "http://area.webServ.project.ar/", className = "ar.project.wclie.area.GetPersonasResponse")
    public java.util.List<ar.project.wclie.area.Persona4Ws> getPersonas();

    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "paises", targetNamespace = "http://area.webServ.project.ar/", className = "ar.project.wclie.area.Paises")
    @WebMethod
    @ResponseWrapper(localName = "paisesResponse", targetNamespace = "http://area.webServ.project.ar/", className = "ar.project.wclie.area.PaisesResponse")
    public ar.project.wclie.area.PaisesResponse.Return paises();
}
