package ar.project.wclie.articles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * Interface provided by this Service
 *
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-21T07:03:07.660-07:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://predic8.com/wsdl/material/ArticleService/1/", name = "ArticleServicePT")
@XmlSeeAlso({ObjectFactory.class})
public interface ArticleServicePT {

    @WebResult(name = "article", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://predic8.com/wsdl/material/ArticleService/1/", className = "ar.project.wclie.articles.GetAllType")
    @WebMethod(action = "getAll_action")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://predic8.com/wsdl/material/ArticleService/1/", className = "ar.project.wclie.articles.GetAllResponseType")
    public java.util.List<ar.project.wclie.articles.ArticleType> getAll();

    @RequestWrapper(localName = "delete", targetNamespace = "http://predic8.com/wsdl/material/ArticleService/1/", className = "ar.project.wclie.articles.DeleteType")
    @WebMethod(action = "delete_action")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://predic8.com/wsdl/material/ArticleService/1/", className = "ar.project.wclie.articles.DeleteResponse")
    public void delete(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebResult(name = "article", targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://predic8.com/wsdl/material/ArticleService/1/", className = "ar.project.wclie.articles.GetType")
    @WebMethod(action = "get_action")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://predic8.com/wsdl/material/ArticleService/1/", className = "ar.project.wclie.articles.GetResponseType")
    public ar.project.wclie.articles.ArticleType get(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebResult(name = "id", targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://predic8.com/wsdl/material/ArticleService/1/", className = "ar.project.wclie.articles.CreateType")
    @WebMethod(action = "create_action")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://predic8.com/wsdl/material/ArticleService/1/", className = "ar.project.wclie.articles.CreateResponseType")
    public java.lang.String create(
        @WebParam(name = "article", targetNamespace = "")
        ar.project.wclie.articles.ArticleType article
    );
}
