package ar.project.wclie.articles;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-21T07:03:07.698-07:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "ArticleService", 
                  wsdlLocation = "http://www.predic8.com:8080/material/ArticleService?wsdl",
                  targetNamespace = "http://predic8.com/wsdl/material/ArticleService/1/") 
public class ArticleService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://predic8.com/wsdl/material/ArticleService/1/", "ArticleService");
    public final static QName ArticleServicePTPort = new QName("http://predic8.com/wsdl/material/ArticleService/1/", "ArticleServicePTPort");
    static {
        URL url = null;
        try {
            url = new URL("http://www.predic8.com:8080/material/ArticleService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ArticleService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.predic8.com:8080/material/ArticleService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ArticleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ArticleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArticleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ArticleService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ArticleService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ArticleService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ArticleServicePT
     */
    @WebEndpoint(name = "ArticleServicePTPort")
    public ArticleServicePT getArticleServicePTPort() {
        return super.getPort(ArticleServicePTPort, ArticleServicePT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArticleServicePT
     */
    @WebEndpoint(name = "ArticleServicePTPort")
    public ArticleServicePT getArticleServicePTPort(WebServiceFeature... features) {
        return super.getPort(ArticleServicePTPort, ArticleServicePT.class, features);
    }

}
