package ar.project.wclie.remote.customer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-02-02T18:39:20.354-03:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", name = "CRMServicePT")
@XmlSeeAlso({ObjectFactory.class})
public interface CRMServicePT {

    @WebResult(name = "customer", targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "ar.project.wclie.remote.customer.GetType")
    @WebMethod(action = "get_action")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "ar.project.wclie.remote.customer.GetResponseType")
    public ar.project.wclie.remote.customer.CustomerType get(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @RequestWrapper(localName = "create", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "ar.project.wclie.remote.customer.CreateType")
    @WebMethod(action = "create_action")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "ar.project.wclie.remote.customer.CreateResponse")
    public void create(
        @WebParam(name = "customer", targetNamespace = "")
        ar.project.wclie.remote.customer.CustomerType customer
    );

    @WebResult(name = "customer", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "ar.project.wclie.remote.customer.GetAllType")
    @WebMethod(action = "getAll_action")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "ar.project.wclie.remote.customer.GetAllResponseType")
    public java.util.List<ar.project.wclie.remote.customer.CustomerType> getAll();
}
