package ar.project.wclie.remote.customer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-02-02T18:39:20.391-03:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "CustomerService", 
                  wsdlLocation = "file:/C:/Users/Pablo/AppData/Local/Temp/tempdir5499385243854275836.tmp/CustomerService_1.wsdl",
                  targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/") 
public class CustomerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://predic8.com/wsdl/crm/CRMService/1/", "CustomerService");
    public final static QName CRMServicePTPort = new QName("http://predic8.com/wsdl/crm/CRMService/1/", "CRMServicePTPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Pablo/AppData/Local/Temp/tempdir5499385243854275836.tmp/CustomerService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Pablo/AppData/Local/Temp/tempdir5499385243854275836.tmp/CustomerService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CRMServicePT
     */
    @WebEndpoint(name = "CRMServicePTPort")
    public CRMServicePT getCRMServicePTPort() {
        return super.getPort(CRMServicePTPort, CRMServicePT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRMServicePT
     */
    @WebEndpoint(name = "CRMServicePTPort")
    public CRMServicePT getCRMServicePTPort(WebServiceFeature... features) {
        return super.getPort(CRMServicePTPort, CRMServicePT.class, features);
    }

}
